### ISSUE TITLE
Encode failure for some strings with non-ascii characters

### ISSUE THREAD

**Issue by tsbehlman** [davalapar/what-the-pack#3]
The string "WALL·E – Typeset in the Future" decodes as "W" and causes further decoding problems if it is contained by an object with other data in it.

This appears to be due to [the fixstr condition in index.js](https://github.com/davalapar/what-the-pack/blob/000ba03a5ba559bf1a35fceb0c1acdbd83fb1f39/index.js#L62), which checks if the number of _characters_ is less than 32, rather than the number of _bytes_ as defined by [the MessagePack spec](https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family) and implemented in decode().  "WALL·E – Typeset in the Future" is 30 characters long but uses 33 bytes in utf8.

**Comment by davalapar** [comment]
Hi @tsbehlman, thanks for this!

Fixed in `1.1.5`, also added `'WALL·E – Typeset in the Future'` in jest test.
